name: release
on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: pjvds/setup-go@v2.1.4
        with:
          stable: true
          go-version: 1.16
      -
        name: Update APT
        run: sudo apt-get -yq update
#      -
#        name: Install Snapcraft
#        run: sudo apt-get -yq --no-install-suggests --no-install-recommends install snapcraft
#      - 
#        name: Login to Snapcraft
#        env:
#          SNAPCRAFT_LOGIN: ${{ secrets.SNAPCRAFT_LOGIN }}
#        run: snapcraft login --with <(printf "$SNAPCRAFT_LOGIN")
      -
        name: Login to GitHub Packages Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          docker login docker.pkg.github.com -u docker --password-stdin
      -
        name: Login to Docker Hub Registry
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | \
          docker login -u pjvds --password-stdin
      -
        name: Dump diff
        run: |
          git diff
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: --debug release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
